### PR TITLE
Update navigation example

### PR DESCRIPTION
**Pull request by jhanca-robotecai**
This PR updates navigation example to run with either ROS 2 Humble or Jazzy. Moreover, it uses RViz instead of a docker with Foxglove. 

Note: this PR is based on the code pushed and tested by @boczekbartek  and @pijaro . ~~I am marking it as a draft, as this PR does not work on my machines (tested on two independent computers 2204+Humble and 2404+Jazzy).~~

### CODE REVIEW

**Comment by knicked** [comment]
Works on my machine with Ubuntu 22.04 and ROS2 Humble.

**Comment by pijaro** [comment]
Just tested this branch on Ubuntu 24.04 and Jazzy - works for me.

@jhanca-robotecai Can you describe your issues? maybe show us some logs?

**Comment by knicked** [comment]
I just tested this as well on 24.04 + Jazzy and it worked, but there seems to be issues when running the Game Launcher using the `run-game.bash` script. The game won't open and the console is being flooded with the following message:
```<15:34:09> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:10> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:11> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
<15:34:11> [Error] (CameraSensor) - Frame capture initialization failed. Frame capture not availble.
```
This occurs both on 2204+Humble and 2404+Jazzy. Removing the `--rhi=null` argument from the script fixed the problem.

**Comment by pijaro** [comment]
@knicked I think that this is expected behavior. (correct me if I'm wrong)

Renderer (`--rhi=null`) is turned off so the simulation can work in a headless mode. The flood error is because the camera tries to render, but can't (because the renderer is off). Maybe printing warnings would be a better choice here, errors are too scary.

Navigation still works with that.

**Comment by knicked** [comment]
I can confirm that navigation works in this setup. However, the ros2 camera sensor mounted on the robot does not work, and it is an integral part of the demo. I think we should find a way to make it work when running headless, or consider not running headless.

**Comment by pijaro** [comment]
In that case, we should use [xvfb-run](https://manpages.ubuntu.com/manpages/noble/man1/xvfb-run.1.html)

```
xvfb-run ./Project/build/linux/bin/profile/RAIROSBotXLDemo.GameLauncher -bg_ConnectToAssetProcessor=0
```

Just checked it on u22 + humble and it works.

**Comment by jhanca-robotecai** [comment]
I updated `.gitignore` file and fixed the game launcher script; I tested it again on my machine and it works correctly - my problems in the running _nav_ were caused by ROS 2 interfaces collision on the network.

**Review by pijaro — APPROVED** [review]

**Review by knicked — APPROVED** [review]

**Pull request merged**
